####### database Config不与SQL分析打印配置一起使用 #######
#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      # driver-class-name: com.mysql.jdbc.Driver
#      connection-init-sqls: set names utf8mb4
#      initial-size: 10
#      max-active: 1000
#      min-idle: 500
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'X'
#      test-while-idle: true
#      test-on-return: false
#      test-on-borrow: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3322/db_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 341125

# Server settings
server:
  port: 8086
  servlet:
    context-path: /boot-mybatis-plus

  #  SQL分析打印
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3322/db_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 341125
