####### database Config不与SQL分析打印配置一起使用 #######
#spring:
#  profiles:
#    include: [center]

# Server settings
server:
  port: 8086
  servlet:
    context-path: /boot-mybatis-plus

  #  SQL分析打印
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3322/db_test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 341125
